vim.cmd("split")
vim.cmd("vsplit")
vim.cmd("vsplit")
vim.cmd("wincmd L")
vim.cmd("split")
vim.cmd("wincmd j")
vim.cmd("vertical resize 50")
vim.cmd("terminal")
vim.cmd("wincmd h")
vim.cmd("terminal")
vim.cmd("wincmd k")
vim.cmd("wincmd l")
vim.cmd("split")
vim.cmd("wincmd j")
vim.cmd("wincmd j")
vim.cmd("resize 10")
vim.cmd("wincmd k")
vim.cmd("vertical resize 125")
vim.cmd("wincmd l")
vim.cmd("resize 30")
